# SPDX-FileCopyrightText: (c) 2026 Toyota Connected North America
# SPDX-License-Identifier: GPLv3
set(TEST_RUNNER_PLUGIN_SRCS "")
set(TEST_RUNNER_PLUGIN_INC "")
set(TEST_RUNNER_PLUGIN_CLIENT_SRCS "")
set(TEST_RUNNER_PLUGIN_CAPNP_SCHEMAS "")

if (ENABLE_PLUGIN_WESTON_SCREENSHOOTER)
	add_subdirectory(weston_screenshooter)
endif ()

set(TEST_RUNNER_PLUGIN_SRCS          
	${TEST_RUNNER_PLUGIN_SRCS}
	${CMAKE_CURRENT_SOURCE_DIR}/plugins.cpp
	PARENT_SCOPE
)
set(TEST_RUNNER_PLUGIN_CLIENT_SRCS   ${TEST_RUNNER_PLUGIN_CLIENT_SRCS}  PARENT_SCOPE)
set(TEST_RUNNER_PLUGIN_INC           ${TEST_RUNNER_PLUGIN_INC}          PARENT_SCOPE)
set(TEST_RUNNER_PLUGIN_CAPNP_SCHEMAS 
	${TEST_RUNNER_PLUGIN_CAPNP_SCHEMAS} 
	${CMAKE_CURRENT_SOURCE_DIR}/plugins.capnp
	PARENT_SCOPE
)
