# SPDX-FileCopyrightText: (c) 2026 Toyota Connected North America
# SPDX-License-Identifier: GPLv3

name: Build MacOS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .github/workflows/build_linux.yml
      - .github/workflows/build_windows.yml
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - .github/workflows/build_linux.yml
      - .github/workflows/build_windows.yml
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15]
        compiler: [gcc, clang]

    env:
      NONINTERACTIVE: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    runs-on: ${{ matrix.os }}

    if: "!contains(github.event.pull_request.labels.*.name, 'ci: skip macos') && !contains(github.event.head_commit.message, '[skip macos]')"

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Environment
        run: |
          echo "Running on macOS version: $(sw_vers -productVersion)"
          echo "Running on architecture: $(uname -m)"
          echo "Current directory: $(pwd)"
          echo "Environment variables:"
          env

      - name: Brew fixup
        run: |
          brew upgrade |true
          brew cleanup |true
          brew doctor |true
          ruby -v

      - name: Configure CMake (gcc)
        if: matrix.compiler == 'gcc'
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_CAPNP=ON \
            -DBUILD_SERVER=OFF \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Configure CMake (clang)
        if: matrix.compiler == 'clang'
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_CAPNP=ON \
            -DBUILD_SERVER=OFF \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        run: |
          export C_INCLUDE_PATH=/usr/local/include
          export CPLUS_INCLUDE_PATH=/usr/local/include
          export LIBRARY_PATH=/usr/local/lib
          cmake --build build

      - name: Publish Binary
        uses: actions/upload-artifact@v4
        with:
            name: test_runner_client_${{ matrix.os }}_${{ matrix.compiler }}
            path: |
              build/libTestRunnerClient.dylib
              build/TestRunnerClientTest
              build/third_party/spdlog-1.12.0/libspdlog.a
